spring:
  kafka:
    listener:
      ack-mode: record
    bootstrap-servers: "localhost:9092"
    producer:
      acks: all
      enable:
        idempotence: true
      consumer:
        auto-offset-reset: earliest
        group-id: demo-api
        enable-auto-commit: false
